services:
  app:
    #image: ghcr.io/nomad-hzb/hzb-bat-image:main
    image: ghcr.io/nomad-hzb/hzb-bat-image:pr-52

  worker:
    #image: ghcr.io/nomad-hzb/hzb-bat-image:main
    image: ghcr.io/nomad-hzb/hzb-bat-image:pr-52
  north:
    #image: ghcr.io/nomad-hzb/hzb-bat-image:main
    image: ghcr.io/nomad-hzb/hzb-bat-image:pr-52

  logtransfer:
    #image: ghcr.io/nomad-hzb/hzb-bat-image:main
    image: ghcr.io/nomad-hzb/hzb-bat-image:pr-52

  jupyterlab_image:
    #image: ghcr.io/nomad-hzb/hzb-bat-image:main
    image: ghcr.io/nomad-hzb/hzb-bat-image:pr-52

