services:
  app:
    image: ghcr.io/nomad-hzb/hzb-bat-image:pr-main

  worker:
    image: ghcr.io/nomad-hzb/hzb-bat-image:pr-main

  north:
    image: ghcr.io/nomad-hzb/hzb-bat-image:pr-main

  logtransfer:
    image: ghcr.io/nomad-hzb/hzb-bat-image:pr-main

  jupyterlab_image:
    image: ghcr.io/nomad-hzb/hzb-bat-image:pr-main

