services:
  app:
    #image: ghcr.io/nomad-hzb/hzb-bat-image:main
    image: ghcr.io/nomad-hzb/hzb-bat-image:pr-41

  worker:
    #image: ghcr.io/nomad-hzb/hzb-bat-image:main
    image: ghcr.io/nomad-hzb/hzb-bat-image:pr-41
  north:
    #image: ghcr.io/nomad-hzb/hzb-bat-image:main
    image: ghcr.io/nomad-hzb/hzb-bat-image:pr-41

  logtransfer:
    #image: ghcr.io/nomad-hzb/hzb-bat-image:main
    image: ghcr.io/nomad-hzb/hzb-bat-image:pr-41

  jupyterlab_image:
    #image: ghcr.io/nomad-hzb/hzb-bat-image:main
    image: ghcr.io/nomad-hzb/hzb-bat-image:pr-41

