services:
  api_host: 'localhost'
  api_base_path: '/nomad-oasis'
  upload_limit: 1000
  admin_user_id: 'e2796594-6a85-4a0b-a7ae-5862505c24d7'
  upload_members_group_search_enabled: true
  api_secret: 'pq63hoNjI0ItKGNquS5DjbLUhea1Jy5x'

fs:
  north_home_external: "/nfs/qumulo-a/nomad05/.nomad_hzb_bat_storage_nomad05/.volumes/fs/north/users"
  public_external: "/nfs/qumulo-a/nomad05/.nomad_hzb_bat_storage_nomad05/.volumes/fs/public"
  staging_external: "/nfs/qumulo-a/nomad05/.nomad_hzb_bat_storage_nomad05/.volumes/fs/staging"
  
logstash:
  enable: false

oasis:
  is_oasis: true
  uses_central_user_management: true

north:
  jupyterhub_crypt_key: '271b13f3ef7023b06277faa49ff4112a572f2f85b52e4c6967511492f036a92d'
  enabled: true
  tools:
    include:
      - voila
      - jupyter2
    options:
      jupyter2:
        short_description: A jupyter webapp container with voila opens notebook
        description: A jupyter hub webapp container with voila installed.
        image: ghcr.io/nomad-hzb/hzb-bat-image/jupyter:main
        path_prefix: lab/tree
        with_path: true
        mount_path: /home/jovyan
        file_extensions:
          - ipynb
        maintainer:
          - name: Michael Götte
            email: michael.goette@helmholtz-berlin.de
      voila:
        short_description: A jupyter webapp container with voila opens voila
        description: A jupyter hub webapp container with voila installed.
        image: ghcr.io/nomad-hzb/hzb-bat-image/jupyter:main
        path_prefix: voila/render
        with_path: true
        mount_path: /home/jovyan
        file_extensions:
          - ipynb
        maintainer:
          - name: Michael Götte
            email: michael.goette@helmholtz-berlin.de

meta:
  deployment: 'oasis'
  deployment_url: 'https://nomad-ce-iees.helmholtz-berlin.de'
  maintainer_email: 'michael.goette@helmholtz-berlin.de'

mongo:
    db_name: nomad_oasis_v1

elastic:
    entries_index: nomad_oasis_entries_v1
    materials_index: nomad_oasis_materials_v1

ui:
  theme:
    title: "NOMAD Batteries HZB"
  unit_systems: 
    selected: "SI"
       
      
plugins:
#   # We only include our schema here. Without the explicit include, all plugins will be
#   # loaded. Many build in plugins require more dependencies. Install nomad-lab[parsing]
#   # to make all default plugins work.
  entry_points:
    exclude: []
    include: []

