services:
  api_host: 'localhost'
  api_base_path: '/nomad-oasis'
  upload_limit: 1000
  admin_user_id: 'see NOMAD_SERVICES_ADMIN_USER_ID value in .env'
  upload_members_group_search_enabled: true
  api_secret: 'see NOMAD_SERVICES_API_SECRET value in .env'

fs:
  north_home_external: "see NOMAD_FS_NORTH_HOME_EXTERNAL value in .env"
  public_external: "see NOMAD_FS_PUBLIC_EXTERNAL value in .env"
  staging_external: "see NOMAD_FS_STAGING_EXTERNAL value in .env"
  
logstash:
  enable: false

oasis:
  is_oasis: true
  uses_central_user_management: true

north:
  jupyterhub_crypt_key: 'see NOMAD_NORTH_JUPYTERHUB_CRYPT_KEY value in .env'
  enabled: true
  tools:
    include:
      - voila
      - jupyter2
    options:
      jupyter2:
        short_description: A jupyter webapp container with voila opens notebook
        description: A jupyter hub webapp container with voila installed.
        image: ghcr.io/nomad-hzb/hzb-bat-image/jupyter:main
        path_prefix: lab/tree
        with_path: true
        mount_path: /home/jovyan
        file_extensions:
          - ipynb
        maintainer:
          - name: Michael Götte
            email: michael.goette@helmholtz-berlin.de
      voila:
        short_description: A jupyter webapp container with voila opens voila
        description: A jupyter hub webapp container with voila installed.
        image: ghcr.io/nomad-hzb/hzb-bat-image/jupyter:main
        path_prefix: voila/render
        with_path: true
        mount_path: /home/jovyan
        file_extensions:
          - ipynb
        maintainer:
          - name: Michael Götte
            email: michael.goette@helmholtz-berlin.de

meta:
  deployment: 'see NOMAD_META_DEPLOYMENT value in .env'
  deployment_url: 'see NOMAD_META_DEPLOYMENT_URL value in .env'
  maintainer_email: 'see NOMAD_META_MAINTAINER_EMAIL value in .env'

mongo:
    db_name: nomad_oasis_v1

elastic:
    entries_index: nomad_oasis_entries_v1
    materials_index: nomad_oasis_materials_v1

ui:
  theme:
    title: "NOMAD Batteries HZB"
  unit_systems: 
    selected: "SI"
      
plugins:
#   # We only include our schema here. Without the explicit include, all plugins will be
#   # loaded. Many build in plugins require more dependencies. Install nomad-lab[parsing]
#   # to make all default plugins work.
  entry_points:
    include: ["nomad_battery_space.schema_packages:bat_schema_package",
              "nomad_battery_space.schema_packages:bat_cell_assembly_package",
              "apps/1_all/1_entries",
              "apps/3_experiment/1_eln",
              "nomad_battery_space.apps:app_entry_point",
              "pynxtools.nomad.entrypoints:nexus_parser",            
              "pynxtools.nomad.entrypoints:nexus_schema",
              "pynxtools.nomad.entrypoints:nexus_data_converter",
              "pynxtools.nomad.entrypoints:nexus_app",
              "pynxtools.nomad.entrypoints:simple_nexus_example",
             ]
